// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBglyim-ZoRC4gF_F79PeM2x8lR3dxCFTM',
    appId: '1:917936271250:web:c336601d169979798ddb4b',
    messagingSenderId: '917936271250',
    projectId: 'auto-checkin-v2',
    authDomain: 'auto-checkin-v2.firebaseapp.com',
    storageBucket: 'auto-checkin-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKA1mms2cGPnc7xsmFanTt170BfU_UcuQ',
    appId: '1:917936271250:android:4647542ae944708d8ddb4b',
    messagingSenderId: '917936271250',
    projectId: 'auto-checkin-v2',
    storageBucket: 'auto-checkin-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALPo0vYhgy6fuVzy7qYIqOZgsPwhhcKu0',
    appId: '1:917936271250:ios:004db4e1edd915538ddb4b',
    messagingSenderId: '917936271250',
    projectId: 'auto-checkin-v2',
    storageBucket: 'auto-checkin-v2.firebasestorage.app',
    iosBundleId: 'com.example.autoCheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALPo0vYhgy6fuVzy7qYIqOZgsPwhhcKu0',
    appId: '1:917936271250:ios:004db4e1edd915538ddb4b',
    messagingSenderId: '917936271250',
    projectId: 'auto-checkin-v2',
    storageBucket: 'auto-checkin-v2.firebasestorage.app',
    iosBundleId: 'com.example.autoCheckin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBglyim-ZoRC4gF_F79PeM2x8lR3dxCFTM',
    appId: '1:917936271250:web:d7b5eed7975fb1cd8ddb4b',
    messagingSenderId: '917936271250',
    projectId: 'auto-checkin-v2',
    authDomain: 'auto-checkin-v2.firebaseapp.com',
    storageBucket: 'auto-checkin-v2.firebasestorage.app',
  );
}
