// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzZYcB9wlGlQ1vW4AkrTnxygSJVY7IEk',
    appId: '1:171634447388:web:91b2418a384b4e63befbd9',
    messagingSenderId: '171634447388',
    projectId: 'checkin-app-55083',
    authDomain: 'checkin-app-55083.firebaseapp.com',
    storageBucket: 'checkin-app-55083.firebasestorage.app',
    measurementId: 'G-P6YRP6F431',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ9Rh5p7of_OS3UUqx-b7U23WpiLaM7iQ',
    appId: '1:171634447388:android:a5fcc18a67f6e3ebbefbd9',
    messagingSenderId: '171634447388',
    projectId: 'checkin-app-55083',
    storageBucket: 'checkin-app-55083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwFeghccBLbsTdFJ-DqLsPDBPANLMP4I',
    appId: '1:171634447388:ios:724c21384b650635befbd9',
    messagingSenderId: '171634447388',
    projectId: 'checkin-app-55083',
    storageBucket: 'checkin-app-55083.firebasestorage.app',
    iosClientId: '171634447388-kcpdcveiur5nji2rkr57h2a20ekurfo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoCheckin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwFeghccBLbsTdFJ-DqLsPDBPANLMP4I',
    appId: '1:171634447388:ios:724c21384b650635befbd9',
    messagingSenderId: '171634447388',
    projectId: 'checkin-app-55083',
    storageBucket: 'checkin-app-55083.firebasestorage.app',
    iosClientId: '171634447388-kcpdcveiur5nji2rkr57h2a20ekurfo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoCheckin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHzZYcB9wlGlQ1vW4AkrTnxygSJVY7IEk',
    appId: '1:171634447388:web:4d42ba4a59a3513cbefbd9',
    messagingSenderId: '171634447388',
    projectId: 'checkin-app-55083',
    authDomain: 'checkin-app-55083.firebaseapp.com',
    storageBucket: 'checkin-app-55083.firebasestorage.app',
    measurementId: 'G-01WZ66WC9B',
  );
}
