name: auto_checkin
description: A Flutter application for managing class attendance and scores.

publish_to: 'none'

version: 1.0.0+1

environment:
  # อัปเดตเวอร์ชัน SDK เพื่อรองรับ package ใหม่
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  
  # ลบ flutterfire_ui ออก และเพิ่ม firebase_ui_auth เข้ามาแทน
  firebase_ui_auth: ^1.2.10 
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
